#!/bin/bash
## The first arg is the porposal: e.g P50155 

if [ $# -ne 1 ]; then echo "Please enter the name of the dir containing the data at proposal level"; exit;
fi
P=$1
#n=$2;
for i in `ls $P`; do 
 n=`echo $i |sed s/-/_/g` 
 cp $P/$i/stdprod/*b2.pha.gz spec_${n}.bgd;
 cp $P/$i/stdprod/*s2.pha.gz spec_${n}.src;
 cp $P/$i/stdprod/*rsp.gz spec_${n}.rsp;
 cp spec_${n}.rsp tmp.rsp.gz; gzip -d tmp.rsp.gz;
 fdelrow tmp.rsp["SPECRESP MATRIX"] 900 1 no yes
 mv tmp.rsp spec_${n}.rsp
 if [ -e "spec_${n}.grp" ]; then rm spec_${n}.grp;fi
 grppha "spec_${n}.src" "spec_${n}.grp" "chkey BACKFILE spec_${n}.bgd&chkey RESPFILE spec_${n}.rsp group min 20&exit"
 #n=`echo "$n+1"|bc`
done



