#!/bin/bash

# syntax: nustar_process INDIR
if [ $# != 1 ] ; then
    echo "Syntax:  nustar_process PATH_TO_OBSID"
    exit 1
fi

# initialize heasoft
source $HEADAS/headas-init.sh


# other parameters
indir=$1
stem=nu`basename ${1}`
outdir=${indir}_p/event_cl
if [ ! -d $outdir ]; then mkdir -p $outdir; fi


# running the pipeline
echo
echo Running pipeline...

nupipeline indir=$indir outdir=$outdir steminput=$stem entrystage=1 \
        exitstage=2 pntra=OBJECT pntdec=OBJECT #saamode=STRICT
### for 404cyg observation ###
#read -p "Run in special setting mode?" answer
#if [ $answer != "yes" ]; then exit;fi
#nupipeline indir=$indir outdir=$outdir steminput=$stem entrystage=1 \
#        exitstage=2 pntra=OBJECT pntdec=OBJECT statusexpr="STATUS==b0000xx00xx0xx000" \
#        cleanflick=no hkevtexpr=NONE

# orbit file needed for light curve barycor
cp $indir/auxil/*orb.fits* $outdir
gzip -d $outdir/*orb*fits*



