#!/bin/bash

mode=$1

if [ -z $mode ]; then

    export SAS_ODF="$PWD"
    cifbuild withccfpath=no analysisdate=now category=XMMCCF fullpath=yes
    export SAS_CCF="$PWD/ccf.cif"
    odfingest odfdir=$SAS_ODF outdir=$SAS_ODF
    exit
fi

export SAS_ODF="$PWD/../odf/"
export SAS_CCF="$SAS_ODF/ccf.cif"

case $mode in
    "pn" )
            #epchain exposure=2
            #epchain exposure=2 runbackground=N keepintermediate=raw withoutoftime=Y
            #epchain exposure=2 runatthkgen=N runepframes=N runbadpixfind=N runbadpix=N
            epchain
            mv *EVL* pn.fits;rm P*
            ;;
    "pn_timing" )
            epchain datamode=TIMING
            mv *EVL* pn.fits; rm P*
            ;;
    "mos" )
            #emchain exposures=2
            emchain
            mv *M1*EVL* m1.fits; mv *M2*EVL* m2.fits;rm P*
            ;;
    "rgs" )
            rgsproc orders='1 2' bkgcorrect=no withmlambdacolumn=yes
            root_1=`ls *R1*SRSPEC1*`
            root_2=`ls *R2*SRSPEC1*`
            cp $root_1 spec_r1.src
            cp $root_2 spec_r2.src
            cp ${root_1/SR/BG} spec_r1.bgd
            cp ${root_2/SR/BG} spec_r2.bgd
            cp ${root_1/SRSPEC/RSPMAT} spec_r1.rsp
            cp ${root_2/SRSPEC/RSPMAT} spec_r2.rsp
            rgscombine pha="spec_r1.src spec_r2.src" bkg="spec_r1.bgd spec_r2.bgd" \
                rmf="spec_r1.rsp spec_r2.rsp" filepha="spec_rgs.src" filebkg="spec_rgs.bgd" \
                filermf="spec_rgs.rsp"
            rm spec_rgs.grp &> /dev/null
            grppha spec_rgs.src spec_rgs.grp "group min 20&exit"
            ;;
    "omf" )
            omfchain
            ;;
    "omi" )  
            omichain omdetectnsigma=5 omdetectdetectextended=no
            ;;
    "omg" )  
            omgchain
            ;;
esac

